# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Created')),
                ('date_modified', models.DateTimeField(auto_now_add=True, verbose_name='Last modified')),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('variable_symbol', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('executor', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
