# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-31 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedtransaction',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='processedtransaction',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified'),
        ),
    ]
