# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedtransaction',
            name='created_at',
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Last modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
