# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20161014_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='executor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='processedtransaction',
            name='variable_symbol',
            field=models.CharField(default='not set', max_length=10),
            preserve_default=False,
        ),
    ]
