# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20161031_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedtransaction',
            name='method',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
