# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_processedtransaction_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedtransaction',
            name='transaction_id',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
