# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-05 16:11
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    EmailTemplate = apps.get_model("konfera", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    text = """Dear {first_name} {last_name},\n\n
order ({order_url}) with your ticket for {event} hasn't been paid.\n\n
Unfortunately your order has expired, and is no longer valid. If you want to come to this event you have to order new ticket.\n\n\n

{event} organizers team."""
    html = """Dear {first_name} {last_name},<br /><br />
<a href="{order_url}">order</a> with your ticket for {event} <em>hasn't been paid</em>.<br /><br />
Unfortunately <strong>your order has expired, and is no longer valid</strong>. If you want to come to this event you have to order new ticket.<br /><br /><br />

{event} organizers team."""
    EmailTemplate.objects.using(db_alias).bulk_create([
        EmailTemplate(name="expired_order_notification", counter=0, text_template=text, html_template=html),
    ])


def reverse_func(apps, schema_editor):
    EmailTemplate = apps.get_model("konfera", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    EmailTemplate.objects.using(db_alias).filter(name="expired_order_notification").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20161127_2250'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
