# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='flag',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
