# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0004_auto_20161015_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
