# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0006_auto_20161031_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
