# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 16:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0007_auto_20161110_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cfp_allowed',
            field=models.BooleanField(default=True, help_text='Is it allowed to submit talk proposals?'),
        ),
        migrations.AddField(
            model_name='event',
            name='cfp_end',
            field=models.DateTimeField(null=True, verbose_name='Call for proposals deadline'),
        ),
        migrations.AddField(
            model_name='event',
            name='coc',
            field=models.TextField(blank=True, verbose_name='Code of Conduct'),
        ),
        migrations.AddField(
            model_name='event',
            name='coc_phone',
            field=models.CharField(blank=True, help_text='Publicly displayed phone to contact organizers.', max_length=20, verbose_name='Code of Conduct contact'),
        ),
        migrations.AddField(
            model_name='event',
            name='coc_phone2',
            field=models.CharField(blank=True, help_text='Publicly displayed phone to contact organizers.', max_length=20, verbose_name='Code of Conduct contact 2'),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Publicly displayed email to contact organizers.', max_length=254, verbose_name='E-mail'),
        ),
    ]
