# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0008_auto_20161113_1609'),
        ('konfera', '0007_auto_20161110_0910'),
    ]

    operations = [
    ]
