# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 08:12
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    EmailTemplate = apps.get_model("konfera", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    text = """Dear {first_name} {last_name},\n\n
              thank you for submitting proposal for {event}.\nYou can edit your submission here: {edit_url}.\n\n
              The call for proposals ends at {end_call}. We will inform you about the acceptance status and further
              details after this date.\n\n\n
              {event} organizers team.\n\n
              {event_url}\n"""
    html = """Dear {first_name} {last_name},<br /><br />
              thank you for submitting proposal for <strong><a href=\"{event_url}\">{event}</a></strong>.<br />
              You can edit your submission <a href="{edit_url}">here</a>.<br /><br />
              The call for proposals ends at {end_call}. We will inform you about the acceptance status and further
              details after this date.<br /><br /><br />
              {event} organizers team.<br />"""
    EmailTemplate.objects.using(db_alias).bulk_create([
        EmailTemplate(name="confirm_proposal", counter=0, text_template=text, html_template=html),
    ])


def reverse_func(apps, schema_editor):
    EmailTemplate = apps.get_model("konfera", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    EmailTemplate.objects.using(db_alias).filter(name="confirm_proposal").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0013_auto_20161126_1152'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
