# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 08:12
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    EmailTemplate = apps.get_model("konfera", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    text = """Dear {first_name} {last_name},\n\n
              thank you for submitting proposal for {event}.\n\n
              We will inform you about the acceptance status and further details as soon as possible.\n\n\n
              PyCon SK team.\n\n
              {event_url}\n"""
    html = """Dear {first_name} {last_name},<br /><br />
              thank you for submitting proposal for <strong><a href=\"{event_url}\">{event}</a></strong>.<br />
              We will inform you about the acceptance status and further details as soon as possible.<br /><br /><br />
              PyCon SK team.<br />"""
    EmailTemplate.objects.using(db_alias).bulk_create([
        EmailTemplate(name="confirm_proposal", counter=0, text_template=text, html_template=html),
    ])


def reverse_func(apps, schema_editor):
    EmailTemplate = apps.get_model("konfera", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    EmailTemplate.objects.using(db_alias).filter(name="confirm_proposal").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0013_auto_20161126_1152'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
