# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0014_auto_20161127_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='companyid',
            field=models.CharField(blank=True, max_length=32, verbose_name='Company ID'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='taxid',
            field=models.CharField(blank=True, max_length=32, verbose_name='Tax ID'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='vatid',
            field=models.CharField(blank=True, max_length=32, verbose_name='VAT ID'),
        ),
    ]
