# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 22:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0016_auto_20161129_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
