# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0018_auto_20161203_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='talk',
            name='language',
            field=models.CharField(choices=[('SK', 'Slovak'), ('CZ', 'Czech'), ('EN', 'English')], default='EN', max_length=2),
        ),
    ]
