# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0019_unpaid_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unpaid_notification_sent_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
