# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0021_order_unpaid_notification_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='image',
            field=models.ImageField(blank=True, upload_to='speaker/'),
        ),
    ]
