# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0022_speaker_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unpaid_notification_sent_amount',
            field=models.IntegerField(default=0),
        ),
    ]
