# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-18 16:11
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    EmailTemplate = apps.get_model("konfera", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    new_text = """Dear {first_name} {last_name},\n\n
order ({order_url}) with your ticket for {event} hasn't been paid yet.\n\n
Please pay for it as soon as possible otherwise your ticket will expire.\n\n\n

{event} organizers team."""
    new_html = """Dear {first_name} {last_name},<br /><br />
<a href="{order_url}">order</a> with your ticket for {event} hasn't been paid yet.<br /><br />
Please pay for it as soon as possible otherwise your ticket will expire.<br /><br /><br />

{event} organizers team."""
    email = EmailTemplate.objects.using(db_alias).get(name="unpaid_order_notification")
    email.text_template = new_text
    email.html_template = new_html
    email.save()


def reverse_func(apps, schema_editor):
    EmailTemplate = apps.get_model("konfera", "EmailTemplate")
    db_alias = schema_editor.connection.alias
    old_text = """Dear {first_name} {last_name},\n\n
order with your ticket for {event} hasn't been paid yet.\n\n
Please pay for it as soon as possible otherwise your ticket will expire.\n\n\n

    {event} organizers team."""
    old_html = """Dear {first_name} {last_name},<br /><br />
order with your ticket for {event} hasn't been paid yet.<br /><br />
Please pay for it as soon as possible otherwise your ticket will expire.<br /><br /><br />

{event} organizers team."""

    email = EmailTemplate.objects.using(db_alias).get(name="unpaid_order_notification")
    email.text_template = old_text
    email.html_template = old_html
    email.save()


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0023_order_unpaid_notification_sent_amount'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
