# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0024_auto_20161218_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='other',
            field=models.TextField(blank=True),
        ),
    ]
