# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0027_auto_20170107_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enc_social_media_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='enc_social_media_meta_tags',
            field=models.TextField(blank=True),
        ),
    ]
