# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0028_auto_20170109_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='title',
            field=models.CharField(blank=True, choices=[('none', ''), ('mr', 'Mr.'), ('ms', 'Ms.'), ('mx', 'Mx.')], default='none', max_length=4),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, choices=[('none', ''), ('mr', 'Mr.'), ('ms', 'Ms.'), ('mx', 'Mx.')], default='none', max_length=4),
        ),
    ]
