# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 20:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0029_auto_20170111_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in minutes. If talk is selected, value will be generated.', validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='talk',
            name='status',
            field=models.CharField(choices=[('cfp', 'Call For Proposals'), ('draft', 'Draft'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=32),
        ),
    ]
