# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 21:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0031_auto_20170204_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in minutes. If talk is selected, value will be generated.', validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
    ]
