# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0032_auto_20170202_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettype',
            name='usage',
            field=models.IntegerField(default=-1, help_text='Number of tickets which can be issued. For unlimited amount use -1.'),
        ),
    ]
