# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic_forms', '0006_auto_20170123_1550'),
        ('konfera', '0029_auto_20170111_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormForTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('form_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.FormModelData')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konfera.Ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
