# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_forms', '0006_auto_20170123_1550'),
        ('konfera', '0029_auto_20170111_2105'),
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireForEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('deadline', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konfera.Event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProxyFormModel',
            fields=[
            ],
            options={
                'verbose_name': 'Questionnaire',
                'proxy': True,
                'verbose_name_plural': 'Questionnaires',
            },
            bases=('dynamic_forms.formmodel',),
        ),
        migrations.CreateModel(
            name='ProxyFormModelDate',
            fields=[
            ],
            options={
                'verbose_name': 'Answer',
                'proxy': True,
                'verbose_name_plural': 'Answers',
            },
            bases=('dynamic_forms.formmodeldata',),
        ),
        migrations.AlterModelOptions(
            name='formforticket',
            options={'verbose_name': 'Answer for a ticket', 'verbose_name_plural': 'Answers for tickets'},
        ),
        migrations.AddField(
            model_name='questionnaireforevent',
            name='questionnaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dynamic_forms.FormModel'),
        ),
    ]
