# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konfera', '0029_auto_20170111_2105'),
        ('questionnaires', '0002_auto_20170124_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireforevent',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='questionnaireforevent',
            unique_together=set([('event', 'slug')]),
        ),
    ]
