from django.conf import settings


def collect_view_data():
    """
    Function collects view_data generated by other functions
    """
    view_data = dict()

    if hasattr(settings, 'GOOGLE_ANALYTICS'):
        view_data['ga'] = settings.GOOGLE_ANALYTICS

    return view_data
